# Welcome to Jekyll!
#

# Build settings
theme: minima

plugins:

paginate: 8
paginate_path: "p/:num"
excerpt_separator: <!--more-->

feed:
  title: challenges.geegle.id
  subtitle: How to Maintain Binary Artifacts
  path: rss.xml

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
